sudo: false

notifications:
  email: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
addons:
  postgresql: "9.5"

cache:
  pip: true
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/
    - $HOME/.tox/
    - .tox
env:
  - ES_VERSION=2.3.1 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz

install:
  - pip install tox coveralls tox-travis
  # Install ES
  - wget -nc ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  # Make sure pip is at the latest version:
  - pip install -U pip

script:
  - tox
after_success:
  - coveralls
before_cache:
    - rm -f .tox/py27-django19/log/*.log
    - rm -f .tox/py34-django19/log/*.log
    - rm -f .tox/py35-django19/log/*.log
    - rm -f .cache/pip/log/*.log
