sudo: false

notifications:
  email: false

language: python
python:
  - '3.5'
  - '3.6'
addons:
  postgresql: "9.5"

install:
  - pip install tox coveralls tox-travis
  # Make sure pip is at the latest version:
  - pip install -U pip

script:
  - tox
after_success:
  - coveralls
