sudo: false

notifications:
  email: false

language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
addons:
  postgresql: "9.5"

cache:
  pip: true
  ccache: true
  directories:
    - /home/travis/virtualenv
    - $HOME/.pip-cache/

env:
  - ES_VERSION=2.3.1 ES_DOWNLOAD_URL=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz

install:
  # Install ES
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  # Make sure pip is at the latest version:
  - pip install -U pip
  # Now install the rest of the required Python packages:
  - CFLAGS="-O0" pip install -r requirements.txt
  - pip install python-coveralls
  # Create a basic general.yml file:
  - sed -r
    -e "s,(YNMP_DB_USER:) .*,\\1 'postgres',"
    -e "s,(SECRET_KEY:) '',\\1 'notatallsecret',"
    conf/general.yml-example > conf/general.yml
  - ./manage.py compilemessages

script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - ./run-tests --coverage
after_success:
  - coveralls
